In [16]:
import numpy as np

In [17]:
A = np.array([[5, 1],
            [3, 3]])

In [18]:
eigVals, eigVecs = np.linalg.eig(A)

In [19]:
eigVals

array([6., 2.])

In [20]:
# 각 컬럼이 하나의 고유벡터를 의미함.
# 첫 컬럼은 x=y이면서 길이가 1인 벡터
# 두번째 컬럼은 3x+y=0을 만족하며 길이가 1인 벡터
eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [21]:
v1 = eigVecs[:, 0]
v2 = eigVecs[:, 1]

In [23]:
v1

array([0.70710678, 0.70710678])

In [24]:
v2

array([-0.31622777,  0.9486833 ])

In [26]:
# 컴퓨터의 특성으로 인해 정확히 1이 나오지 않을 수 있음
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

0.9999999999999999
0.9999999999999999


In [28]:
np.linalg.matrix_rank(A)

2

고유값과 행렬식의 관계

In [29]:
singular_mat = np.array([[1, 2],
                        [2, 4]])

In [30]:
np.linalg.eig(singular_mat)

(array([0., 5.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [31]:
np.linalg.det(singular_mat)

0.0

In [32]:
np.linalg.matrix_rank(singular_mat)

1

In [33]:
np.linalg.inv(singular_mat)

LinAlgError: Singular matrix

대칭행렬의 고유벡터는 서로 수직

In [23]:
symm_mat = np.array([[1, 2],
                [2, 1]])

In [24]:
evalues, evectors= np.linalg.eig(symm_mat)

In [25]:
evectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [26]:
np.dot(evectors[:,0], evectors[:,1])

0.0

# Eigendecomposition

In [34]:
import numpy as np

In [50]:
A = np.array([[5, 1],
            [3, 3]])

In [36]:
eigVals, eigVecs = np.linalg.eig(A)

In [39]:
eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [40]:
V = eigVecs

In [41]:
V

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [42]:
eigVals

array([6., 2.])

In [43]:
Lamda = np.diag(eigVals) # 대각행렬 생성 function

In [46]:
Lamda

array([[6., 0.],
       [0., 2.]])

eigendecomposition

In [47]:
np.linalg.matrix_rank(V)

2

In [49]:
np.dot(V, Lamda).dot(np.linalg.inv(V))

array([[5., 1.],
       [3., 3.]])

### When A is a symmetric matrix, then A-1 = A.T

In [25]:
C = np.array([[5, 1],
            [1, 3]])

In [26]:
eigVals1, eigVecs1 = np.linalg.eig(C)

In [29]:
eigVecs1.T

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])

In [30]:
np.linalg.inv(eigVecs1)

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])