Feature scaling,
독립변수 정규화

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('training_test_data.csv')

In [3]:
data.head()

Age  Gender  Experience  Income
0   50       1          15     180
1   29       1           5     163
2   36       1           6     134
3   34       2           4     132
4   46       1           9     188

In [4]:
data_np = data.values

In [5]:
np.random.shuffle(data_np) #데이터를 random하게 다시 섞기

In [6]:
# 종속변수와 독립변수 데이터 분리하기
y = data_np[:,-1]
X = data_np[:,:-1]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [9]:
X_train.shape

(70, 3)

In [10]:
X_test.shape

(30, 3)

In [11]:
X_test

array([[30,  2,  2],
       [31,  2,  4],
       [23,  2,  2],
       [50,  2, 21],
       [32,  1,  3],
       [46,  1, 13],
       [41,  2, 15],
       [47,  2, 21],
       [57,  2, 29],
       [58,  2, 29],
       [55,  1, 26],
       [28,  2,  2],
       [24,  2,  2],
       [50,  1, 20],
       [38,  1, 11],
       [30,  1,  2],
       [46,  1,  9],
       [33,  1,  3],
       [40,  1, 13],
       [28,  1,  1],
       [59,  2, 33],
       [26,  1,  1],
       [28,  2,  2],
       [57,  2, 29],
       [55,  2, 25],
       [30,  2,  1],
       [26,  2,  8],
       [52,  2, 27],
       [23,  1,  5],
       [51,  2, 26]])

## Feature scaling

### standardization

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X_train_std = scaler.fit_transform(X_train) # 학습데이터 존재하는 평균과 표준편차를 얻어냄
X_test_std = scaler.transform(X_test) # 학습데이터에서 얻은 값을 평가데이터에 적용시킴, fit 을 뺀 transform만 사용.
# -> x_test에 fit_transform을 해도 에러는 안남. 근데 그렇게 되면 따로따로 scaling을 하는 꼴이기 때문에 옳지 못함


# 평가데이터는 학습데이터에 얻어진 평균과 표준 편차를 가지고 평가 데이터에 존재하는 독립변수를 표준화시킴.
# 평가데이터는 학습의 결과로 도출된 모형의 성능을 평가하기 위해 사용함.
# 학습 / 평가 데이터의 표준화를 따로따로 하면 표준화 이후 값이 달라지는 경우가 생김. -> 모형의 제대로된 평가가 불가능
# 그렇기 때문에 학습 데이터로 scaling된 정보를 이용해 평가 데이터도 scaling함

# 전체 데이터를 가지고 feature scaling을 하면 안되나??
# -> 평가 데이터는 학습에 사용되면 안됨. 전체 데이터로 표준화를 하게 되면 평가데이터로 사용되는 정보가 반영되어버림.
# -> 학습 데이터와 연관되기 때문에 모형의 성능이 훨씬 좋은 것처럼 나오게 됨(이걸 overfitting이라고 이해할 수 있나?)

In [14]:
X_train_std

array([[-0.36752833, -0.89155583, -0.35581573],
       [ 1.18919996,  1.12163475,  1.12088988],
       [-0.4494614 ,  1.12163475, -0.84805094],
       [ 1.10726689, -0.89155583,  1.21933692],
       [ 1.18919996, -0.89155583,  1.21933692],
       [ 0.77953462,  1.12163475,  0.33331355],
       [-0.94105981, -0.89155583, -0.65115686],
       [-0.03979606,  1.12163475, -0.15892165],
       [ 1.02533382,  1.12163475,  0.9239958 ],
       [ 0.45180235, -0.89155583,  0.43176059],
       [ 1.51693223, -0.89155583,  1.81001917],
       [-0.77719368, -0.89155583, -0.94649798],
       [ 0.86146769,  1.12163475,  1.02244284],
       [-0.12172913,  1.12163475, -0.15892165],
       [-0.61332754, -0.89155583, -0.55270982],
       [-1.18685902,  1.12163475, -1.04494502],
       [ 1.68079837, -0.89155583,  2.10536029],
       [ 1.68079837, -0.89155583,  2.10536029],
       [-1.02299288,  1.12163475, -1.04494502],
       [-1.43265822,  1.12163475, -1.04494502],
       [-0.36752833,  1.12163475, -0.749

In [49]:
X_test_std

array([[-0.23319728, -1.02899151, -0.57455739],
       [ 1.46383242,  0.97182532,  1.51227842],
       [-1.44536135,  0.97182532, -1.04883826],
       [ 1.6254543 , -1.02899151,  1.98655929],
       [-0.39481915,  0.97182532, -0.76426974],
       [ 0.65572304,  0.97182532,  0.56371669],
       [-0.47563009, -1.02899151, -0.47970122],
       [-0.96049572, -1.02899151, -0.66941357],
       [-1.20292854,  0.97182532, -1.04883826],
       [ 1.6254543 , -1.02899151,  1.98655929],
       [-0.0715754 ,  0.97182532, -0.1951327 ],
       [-0.31400822, -1.02899151, -0.66941357],
       [-0.0715754 , -1.02899151, -0.10027653],
       [-1.44536135,  0.97182532, -1.04883826],
       [ 0.00923554, -1.02899151, -0.1951327 ],
       [ 1.46383242, -1.02899151,  1.70199077],
       [ 1.14058867, -1.02899151,  1.13285373],
       [-0.63725197,  0.97182532, -0.76426974],
       [ 0.5749121 , -1.02899151, -0.00542035],
       [ 0.89815585, -1.02899151,  0.75342904],
       [ 0.00923554, -1.02899151, -0.574

In [50]:
from sklearn.linear_model import LinearRegression
model_std = LinearRegression()

In [51]:
model_std.fit(X_train_std, y_train)

LinearRegression()

In [53]:
model_std.score(X_test_std, y_test)

0.5981380889022867

### min-max scaling

In [59]:
from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()
# min-max 스케일링은 학습 데이터를 통해 0-1 사이의 값을 만들지만,
# 평가데이터의 경우 학습데이터에서 얻어진 정보를 이용해 평가데이터의 독립변수를 minmax 시키기 때문에
# 평가데이터는 0-1 사이 안에 있지 않을 수 있다. (벗어날 수 있다. 근데 그래도 상관 없다)
# 평가 데이터가 갖는 값의 범위가 학습데이터와 동일하지 않을 경우 0-1을 벗어날 수 있음

scaling 이후 , 독립변수 수가 적거나 데이터가 너무 적을 경우, 어떤 데이터를 다루느냐에 따라 scaling을 사용 안하는것이 값이 더 잘 나올수도 있다.
-> 최종적으로 모형의 성능이 좋게 나오는 방법을 선택하는것이 답이다.


In [60]:
X_train_minmax = scaler_minmax.fit_transform(X_train)
X_test_minmax = scaler_minmax.transform(X_test)

In [61]:
X_test_minmax

array([[ 0.36842105,  0.        ,  0.18181818],
       [ 0.92105263,  1.        ,  0.84848485],
       [-0.02631579,  1.        ,  0.03030303],
       [ 0.97368421,  0.        ,  1.        ],
       [ 0.31578947,  1.        ,  0.12121212],
       [ 0.65789474,  1.        ,  0.54545455],
       [ 0.28947368,  0.        ,  0.21212121],
       [ 0.13157895,  0.        ,  0.15151515],
       [ 0.05263158,  1.        ,  0.03030303],
       [ 0.97368421,  0.        ,  1.        ],
       [ 0.42105263,  1.        ,  0.3030303 ],
       [ 0.34210526,  0.        ,  0.15151515],
       [ 0.42105263,  0.        ,  0.33333333],
       [-0.02631579,  1.        ,  0.03030303],
       [ 0.44736842,  0.        ,  0.3030303 ],
       [ 0.92105263,  0.        ,  0.90909091],
       [ 0.81578947,  0.        ,  0.72727273],
       [ 0.23684211,  1.        ,  0.12121212],
       [ 0.63157895,  0.        ,  0.36363636],
       [ 0.73684211,  0.        ,  0.60606061],
       [ 0.44736842,  0.        ,  0.181

In [62]:
model_minmax = LinearRegression()
model_minmax.fit(X_train_minmax, y_train)

LinearRegression()

In [63]:
model_minmax.score(X_test_minmax, y_test)

0.5981380889022867